"use client";
import { useState, useRef } from "react";
import { Sparkles, FileText, ArrowLeft, Copy, Check, RefreshCw, FileUp, ChevronDown } from "lucide-react";

const TPL = {
  se: { title: "Software Engineer", text: "We are looking for a Software Engineer.\n\nRequirements:\n- Bachelors in CS\n- 3+ years backend\n- Python/Java/Go\n- Cloud experience" },
  pm: { title: "Product Manager", text: "We are seeking a Product Manager.\n\nRequirements:\n- 3+ years PM\n- Analytical skills\n- Agile" },
  mkt: { title: "Marketing Manager", text: "We are looking for a Marketing Manager.\n\nRequirements:\n- 3+ years marketing\n- SEO/SEM\n- Analytics" },
  ds: { title: "Data Scientist", text: "We are hiring a Data Scientist.\n\nRequirements:\n- MS/PhD\n- 2+ years\n- Python/SQL/ML" },
  ux: { title: "UI/UX Designer", text: "We are looking for a UI/UX Designer.\n\nRequirements:\n- 2+ years\n- Figma\n- Portfolio" },
};

export default function UploadPage() {
  const [t,setT]=useState("");const[j,setJ]=useState("");const[fn,setFn]=useState("");const[r,setR]=useState(null);
  const[ld,setLd]=useState(false);const[er,setEr]=useState("");const[dg,setDg]=useState(false);
  const[st,setSt]=useState(false);const[tb,setTb]=useState("resume");const fr=useRef(null);
  const hf=async f=>{setFn(f.name);setT(await f.text())};
  const go=async()=>{setLd(true);setEr("");setR(null);try{
    const x=await fetch("/api/optimize",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({resume:t,jobDescription:j,generateCoverLetter:tb==="both"})});
    const d=await x.json();if(!x.ok)throw Error(d.error);const p=d.result.split("COVER_LETTER_SEPARATOR");setR({o:p[0].trim(),cl:p[1]?.trim()||""})
  }catch(e){setEr(e.message)}finally{setLd(false)}};
  if(r)return(<div className="min-h-screen bg-gray-50"><header className="border-b bg-white px-6 h-14 flex items-center justify-between"><button onClick={()=>setR(null)} className="flex items-center gap-2 text-gray-600"><ArrowLeft className="w-4 h-4"/>Back</button><span className="text-sm text-green-600"><Check className="w-4 h-4"/>Optimized</span></header><main className="max-w-5xl mx-auto px-4 py-8"><div className="grid md:grid-cols-2 gap-6"><div><h2 className="text-xs font-semibold text-gray-400 mb-3 uppercase">Original</h2><div className="bg-white rounded-xl border p-5 text-sm whitespace-pre-wrap max-h-[600px] overflow-y-auto">{t}</div></div><div><div className="flex items-center justify-between mb-3"><h2 className="text-xs font-semibold text-blue-600 uppercase">Optimized</h2><button onClick={()=>{navigator.clipboard.writeText(r.o)}}><Copy className="w-4 h-4"/></button></div><div className="bg-white rounded-xl border border-blue-200 p-5 text-sm whitespace-pre-wrap max-h-[600px] overflow-y-auto">{r.o}</div></div></div>{r.cl&&<div className="mt-8"><h2 className="text-xs font-semibold text-gray-500 mb-3 uppercase">Cover Letter</h2><div className="bg-white rounded-xl border p-5 text-sm whitespace-pre-wrap">{r.cl}</div></div>}<button onClick={()=>setR(null)} className="mt-6 w-full bg-blue-600 text-white py-3 rounded-xl font-medium">Try Another</button></main></div>);
  return(<div className="min-h-screen bg-gradient-to-b from-white to-gray-50"><nav className="border-b bg-white/80 px-6 h-14 flex items-center justify-between"><a href="/" className="flex items-center gap-2 font-semibold"><FileText className="w-5 h-5 text-blue-600"/>ResumeAI</a><a href="/" className="text-sm text-gray-500">Home</a></nav><main className="max-w-3xl mx-auto px-4 py-10"><h1 className="text-3xl font-bold text-center mb-8">Optimize Your Resume</h1><div className="bg-white rounded-2xl border shadow-sm p-6"><div className="flex gap-1 mb-6 bg-gray-100 p-1 rounded-lg w-fit"><button onClick={()=>setTb("resume")} className={"px-4 py-2 text-sm rounded-md font-medium "+(tb==="resume"?"bg-white shadow":"text-gray-500")}>Resume</button><button onClick={()=>setTb("both")} className={"px-4 py-2 text-sm rounded-md font-medium "+(tb==="both"?"bg-white shadow":"text-gray-500")}>+Cover Letter</button></div><div><div className="flex items-center justify-between mb-2"><label className="text-sm font-medium text-gray-700">Job Description</label><div className="relative"><button onClick={()=>setSt(!st)} className="flex items-center gap-1 text-xs text-blue-600 bg-blue-50 px-3 py-1.5 rounded-full"><ChevronDown className={"w-3 h-3 "+(st?"rotate-180":"")}/>Use Template</button>{st&&<div className="absolute right-0 top-8 w-48 bg-white rounded-xl border shadow-lg z-20 py-1">{Object.entries(TPL).map(([k,v])=><button key={k} onClick={()=>{setJ(v.text);setSt(false)}} className="w-full text-left px-4 py-2 text-sm hover:bg-gray-50">{v.title}</button>)}</div>}</div></div><textarea value={j} onChange={e=>setJ(e.target.value)} placeholder="Paste job description or use a template..." rows={5} className="w-full border rounded-xl p-4 text-sm focus:ring-2 focus:ring-blue-500 outline-none mb-4"/></div><div><label className="text-sm font-medium text-gray-700 mb-2 block">Your Resume</label><div onClick={()=>fr.current?.click()} onDrop={e=>{e.preventDefault();var f=e.dataTransfer.files[0];if(f)hf(f)}} onDragOver={e=>{e.preventDefault();setDg(true)}} onDragLeave={()=>setDg(false)} className={"border-2 border-dashed rounded-xl p-6 text-center cursor-pointer "+(dg?"border-blue-500 bg-blue-50":"border-gray-300")}><input ref={fr} type="file" accept=".txt,.docx" onChange={e=>e.target.files[0]&&hf(e.target.files[0])} className="hidden"/><FileUp className="w-8 h-8 mx-auto mb-2 text-gray-400"/><p>{fn||"Drop or click"}</p></div><textarea value={t} onChange={e=>setT(e.target.value)} placeholder="Or paste resume text here..." rows={8} className="w-full border rounded-xl p-4 text-sm focus:ring-2 focus:ring-blue-500 outline-none mt-3"/></div>{er&&<div className="bg-red-50 text-red-600 text-sm p-3 rounded-xl mb-4">{er}</div>}<button onClick={go} disabled={ld||!t.trim()||!j.trim()} className="w-full bg-blue-600 text-white py-3.5 rounded-xl font-medium disabled:opacity-50">{ld?"Optimizing...":"Optimize Resume"}</button></div></main></div>);
}